version: 2
sources:
  - name: public
    schema: public
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: "UpdatedAt"
    tables:
      - name: manager_departments
        freshness:
      - name: payments
        freshness: