version: '2'
services:
  pg_oltp:
    image: postgres:14
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=oltp
    command:
     - "postgres"
     - "-c"
     - "wal_level=logical" 