dbt_proj: # this needs to match the profile: in your dbt_project.yml file
  target: prod

  outputs:
    prod:
      type: postgres
      host: localhost # первый
      user: postgresuser
      password: postgrespw
      port: 5432
      dbname: oltp
      schema: public
      threads: 8
      keepalives_idle: 120 # default 0, indicating the system default. See below
      connect_timeout: 7200 # default 10 seconds
config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True
  fail_fast: False